DRIVER_CLASS=com.mysql.cj.jdbc.Driver
DB_USER=apsode
DB_CONNECTION_URL=jdbc:mysql://100.101.10.83:3306/fusion-project?characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
DB_PWD=kunbolee0212@